/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author Princ
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddUSer = new javax.swing.JButton();
        RemoveNode = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        showGraph = new javax.swing.JButton();
        seeIsles = new javax.swing.JToggleButton();
        bridgeCheck = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddUSer.setBackground(new java.awt.Color(0, 0, 255));
        AddUSer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddUSer.setForeground(new java.awt.Color(255, 255, 255));
        AddUSer.setText("Add friend");
        AddUSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUSerActionPerformed(evt);
            }
        });
        jPanel1.add(AddUSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        RemoveNode.setBackground(new java.awt.Color(0, 0, 255));
        RemoveNode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveNode.setForeground(new java.awt.Color(255, 255, 255));
        RemoveNode.setText("Remove friend");
        jPanel1.add(RemoveNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        loadFile.setBackground(new java.awt.Color(0, 0, 255));
        loadFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadFile.setForeground(new java.awt.Color(255, 255, 255));
        loadFile.setText("Load Files");
        jPanel1.add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        showGraph.setBackground(new java.awt.Color(0, 0, 255));
        showGraph.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showGraph.setForeground(new java.awt.Color(255, 255, 255));
        showGraph.setText("Show Graph");
        jPanel1.add(showGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        seeIsles.setBackground(new java.awt.Color(0, 0, 255));
        seeIsles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seeIsles.setForeground(new java.awt.Color(255, 255, 255));
        seeIsles.setText("See isles");
        seeIsles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeIslesActionPerformed(evt);
            }
        });
        jPanel1.add(seeIsles, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        bridgeCheck.setBackground(new java.awt.Color(0, 0, 255));
        bridgeCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bridgeCheck.setForeground(new java.awt.Color(255, 255, 255));
        bridgeCheck.setText("See Bridges");
        jPanel1.add(bridgeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("UNSOCIAL SOCIAL NETWORK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jScrollPane1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jScrollPane1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 250, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Princ\\OneDrive\\Pictures\\MINI.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seeIslesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeIslesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seeIslesActionPerformed

    private void AddUSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUSerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUSerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUSer;
    private javax.swing.JButton RemoveNode;
    private javax.swing.JToggleButton bridgeCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadFile;
    private javax.swing.JToggleButton seeIsles;
    private javax.swing.JButton showGraph;
    // End of variables declaration//GEN-END:variables
}
