/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import File_management.File_m;

/**
 *
 * @author david
 */
public class MainGUI extends javax.swing.JFrame {
    File_m archivo = new File_m();
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        File_m archivo = new File_m();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Load_file = new javax.swing.JButton();
        LoadUser = new javax.swing.JButton();
        LoadRelation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Load_file.setText("Cargar Archivo");
        Load_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_fileActionPerformed(evt);
            }
        });
        jPanel1.add(Load_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 50));

        LoadUser.setText("Cargar Usuario");
        jPanel1.add(LoadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 40));

        LoadRelation.setText("Cargar Relacion");
        jPanel1.add(LoadRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 40));

        ShowInfo.setColumns(20);
        ShowInfo.setRows(5);
        jScrollPane1.setViewportView(ShowInfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 250, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Load_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_fileActionPerformed
        // TODO add your handling code here:
        archivo.load_file();
        String aux = "";
        
        
    }//GEN-LAST:event_Load_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadRelation;
    private javax.swing.JButton LoadUser;
    private javax.swing.JButton Load_file;
    private javax.swing.JTextArea ShowInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
